[workspace]
resolver = "2"

members = [
    "basic-fee-handler",
    "bridge",
    "traits",
    "substrate-node/node",
    "substrate-node/runtime",
]

exclude = [

]

[profile.release]
panic = "unwind"