# The Licensed Work is (c) 2022 Sygma
# SPDX-License-Identifier: LGPL-3.0-only

name: Create Sygma substrate pallet release

on:
  push:
    branches:
      - main
jobs:
  release-please:
    name: release
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:

      - uses: actions/checkout@v2
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          token: ${{ secrets.RELEASE_TOKEN }}
          command: manifest
          default-branch: main
